# Generated by Django 3.2.4 on 2021-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_API', '0002_remove_datastock_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.TextField()),
                ('Close', models.FloatField()),
                ('PointChange', models.FloatField()),
                ('PercentageChange', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubIndex', models.TextField()),
                ('Turnover', models.FloatField()),
                ('Close', models.FloatField()),
                ('PointChange', models.FloatField()),
                ('PercentageChange', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopGainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.TextField()),
                ('LTP', models.FloatField()),
                ('PointChange', models.FloatField()),
                ('PercentageChange', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopLoosers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.TextField()),
                ('LTP', models.FloatField()),
                ('PointChange', models.FloatField()),
                ('PercentageChange', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopTradedShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.TextField()),
                ('Volumn', models.BigIntegerField()),
                ('LTP', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopTurnOvers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.TextField()),
                ('TurnOvers', models.BigIntegerField()),
                ('LTP', models.FloatField()),
            ],
        ),
    ]
